### ISSUE TITLE
errors appeared when installing kaldifst

### ISSUE THREAD

**Issue by AlsiaTang** [k2-fsa/kaldifst#41]
Hi ! I am installing kaldifst with the source code using command ' python3 setup.py install ' , but during compiling ,some errors appear:
I tried to upgrade my cmake from version 3.17 to 3.25, but it did not work . And it confuses me several days . Could you help me solve this problem ? Thank you !
<img width="733" alt="error" src="https://user-images.githubusercontent.com/111488901/210918561-fe9a57cb-5c29-4459-96fa-a09dc4973216.PNG">

**Comment by AlsiaTang** [comment]
I have  tried gcc-4.8,gcc-5.4,gcc-7.3, this error still exists

**Comment by csukuangfj** [comment]
> I have tried gcc-4.8,gcc-5.4,gcc-7.3, this error still exists

when you switch to a new version of GCC, did you remove the build directory? also, could you verify that the log output indeed shows it is using the expected gcc?

**Comment by AlsiaTang** [comment]
I remove the build history using command 'python3 setup.py clean' .This log belongs to gcc -7.3, gcc-4.8 will fail at the  very begining

**Comment by csukuangfj** [comment]
Could you post the text error logs so that I can copy the?

**Comment by AlsiaTang** [comment]
I am sorry I can not post the full log , beacause I am installing it on the  internal network. But I am wondering if it is the version of openfst that caused this error . The openfst url in cmake/openfst.cmake is :'https://github.com/kkm000/openfst/archive/refs/tags/win/1.6.5.1.tar.gz' , but it can not be accessed in kkm000's git .  So I replaced it with the latest version: "https://github.com/kkm000/openfst"

**Comment by csukuangfj** [comment]
Please download it from
https://pan.baidu.com/s/1ExVSOyItRG3GYjZKnAmHuQ?pwd=d3w4

Suppose that you place it inside `/tmp`, then you need to change
https://github.com/k2-fsa/kaldifst/blob/293d6986f2a3fe94b18264e2e588e3042e8356ed/cmake/openfst.cmake#L6
to
```
 set(openfst_URL  "file:///tmp/openfst-win-1.6.5.1.tar.gz") 
```

---

Please don't change the version of OpenFst. Other versions are not verified.

**Comment by AlsiaTang** [comment]
The error occurs when building fstcript
<img width="614" alt="1" src="https://user-images.githubusercontent.com/111488901/210942896-51c3e325-a3c1-4aa4-8be8-7d114f39f15d.PNG">
<img width="674" alt="2" src="https://user-images.githubusercontent.com/111488901/210943065-bcc7b396-9864-4a75-a704-739e4d2c0651.PNG">
<img width="735" alt="3" src="https://user-images.githubusercontent.com/111488901/210943328-dc2c7b49-dfd9-4dfb-b5d7-4ac33cb966bb.PNG">

**Comment by csukuangfj** [comment]
which version of openfst are you using? Did you change any code?

**Comment by AlsiaTang** [comment]
I used the openfst downloaded from the  link you offered just now , the error is the same  /(ㄒoㄒ)/

**Comment by csukuangfj** [comment]
Please first delete the `build` folder and run

```
mkdir build
cd build
cmake ..
make
```

and post the output of the above commands.

(Please post text error logs)

**Comment by AlsiaTang** [comment]
I using the following command :
mkdir build
cd build
cmake ..
make
the kaldifst is installed successfully , that really solve my problem! Thank you very much ! 谢谢大神

**Comment by csukuangfj** [comment]
please use
```
cd build
export PYTHONPATH=$PWD/lib:$PWD/../kaldifst/python:$PYTHONPATH
```
so that you can use
```
import kaldifst
```
in Python.

**Comment by AlsiaTang** [comment]
OK ！

**Comment by csukuangfj** [comment]
The reason is that you are not using `python3 setup.py install`.
You have to set the environment variable `PYTHONPATH`.

**Comment by AlsiaTang** [comment]
When I add variable PYTHONPATH of kaldifst to my bashrc ,  it can  import kaldifst successfully. But when I am installing icefall , it still shows kaldifst not found. It's weird .
<img width="808" alt="5" src="https://user-images.githubusercontent.com/111488901/210960278-0146ebcd-86dc-40e4-b809-2788c474c232.PNG">

**Comment by csukuangfj** [comment]
Can you check that PYTHONPATH is still set when you install icefall?
```
echo $PYTHONPATH
```

**Comment by AlsiaTang** [comment]
It's still set
<img width="650" alt="6" src="https://user-images.githubusercontent.com/111488901/210968055-a3552084-ae56-4461-9641-67e366ceb769.PNG">

**Comment by csukuangfj** [comment]
How do you install `icefall`?
Are you following https://k2-fsa.github.io/icefall/installation/index.html

**Comment by csukuangfj** [comment]
You can remove `kaldifst` from the requirements.txt of `icefall`.

**Comment by AlsiaTang** [comment]
OK, I will try

**Comment by csukuangfj** [comment]
@AlsiaTang 

Have you succeeded in running icefall?

**Comment by AlsiaTang** [comment]
Yeah, I've installed icefall  and run the sample code of aishell  successfully (￣▽￣)／
